=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/08_XMLText/811_01.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by tester (altova) --><xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">  <xs:element name="nds">    <xs:complexType>      <xs:sequence>        <xs:element name="input">          <xs:complexType>            <xs:sequence>              <xs:element name="add">                <xs:complexType>                  <xs:sequence>                    <xs:element name="add-attr" maxOccurs="unbounded">                      <xs:complexType>                        <xs:sequence>                          <xs:element name="value">                            <xs:complexType>                              <xs:simpleContent>                                <xs:extension base="xs:string">                                  <xs:attribute name="type" type="xs:string" use="required"/>                                </xs:extension>                              </xs:simpleContent>                            </xs:complexType>                          </xs:element>                        </xs:sequence>                        <xs:attribute name="attr-name" type="xs:string" use="required"/>                      </xs:complexType>                    </xs:element>                  </xs:sequence>                  <xs:attribute name="class-name" type="xs:string" use="required"/>                  <xs:attribute name="src-dn" type="xs:string" use="required"/>                  <xs:attribute name="event-id" type="xs:boolean" use="required"/>                </xs:complexType>              </xs:element>            </xs:sequence>          </xs:complexType>        </xs:element>      </xs:sequence>      <xs:attribute name="dtdversion" type="xs:decimal" use="required"/>      <xs:attribute name="ndsversion" type="xs:decimal" use="required"/>    </xs:complexType>  </xs:element></xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/08_XMLText/811_02.xml
<?xml version="1.0" encoding="UTF-8"?><nds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="811_01.xsd" dtdversion="1.1" ndsversion="8.5">  <input>    <add class-name="User" src-dn="Anton Ebenhof" event-id="0">      <add-attr attr-name="Surname">        <value type="string">Ebenhof</value>      </add-attr>      <add-attr attr-name="Country">        <value type="string">DE</value>      </add-attr>      <add-attr attr-name="Location">        <value type="string">Essen</value>      </add-attr>      <add-attr attr-name="Telephone Number">        <value type="string">+49 201 5552-474</value>      </add-attr>    </add>  </input></nds>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/08_XMLText/811_01.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Ausgabe von Telefonanalage -->
<?xml-stylesheet type="text/xsl" href="811_01.xslt"?>
<nds dtdversion="1.1" ndsversion="8.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="811_01.xsd">
  <input>
    <add class-name="User" src-dn="Anton Ebenhof" event-id="0">
      <add-attr attr-name="Given Name">
        <value type="string">Anton</value>
      </add-attr>
      <add-attr attr-name="Surname">
        <value type="string">Ebenhof</value>
      </add-attr>
      <add-attr attr-name="Country">
        <value type="string">DE</value>
      </add-attr>
      <add-attr attr-name="Location">
        <value type="string">Essen</value>
      </add-attr>
      <add-attr attr-name="Stammnummer">
        <value type="string">555</value>
      </add-attr>
      <add-attr attr-name="Nebenstellennummer">
        <value type="string">2-474</value>
      </add-attr>
    </add>
  </input>
</nds>
