=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/16_Abfragen/1612_01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Posten">
    <xs:complexType>
      <xs:attribute name="P_Nr" type="xs:string" use="required"/>
      <xs:attribute name="R_Nr" type="xs:string" use="required"/>
      <xs:attribute name="P_Summe" type="xs:string" use="required"/>
      <xs:attribute name="T_Nr" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Rechnung">
    <xs:complexType>
      <xs:attribute name="R_Nr" type="xs:string" use="required"/>
      <xs:attribute name="R_Datum" type="xs:string" use="required"/>
      <xs:attribute name="R_Summe" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tarif">
    <xs:complexType>
      <xs:attribute name="T_Nr" type="xs:string" use="required"/>
      <xs:attribute name="T_Name" type="xs:string" use="required"/>
      <xs:attribute name="T_GueBis" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Umsatzliste">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Rechnungsliste">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="Rechnung" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Postenliste">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="Posten" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Tarifliste">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="Tarif" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/16_Abfragen/1612_01.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="613_01.xslt"?>
<Umsatzliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1612_01.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <Rechnungsliste>
    <Rechnung R_Nr="7" R_Datum="31.03.03" R_Summe="8.61"/>
    <Rechnung R_Nr="8" R_Datum="31.03.03" R_Summe="5.85"/>
    <Rechnung R_Nr="9" R_Datum="31.03.03" R_Summe="4.69"/>
    <Rechnung R_Nr="113" R_Datum="31.05.03" R_Summe="1.42"/>
    <Rechnung R_Nr="114" R_Datum="31.05.03" R_Summe="4.57"/>
    <Rechnung R_Nr="115" R_Datum="31.05.03" R_Summe="19.16"/>
  </Rechnungsliste>
  <Postenliste>
    <Posten P_Nr="33" R_Nr="7" P_Summe="2.28" T_Nr="2"/>
    <Posten P_Nr="34" R_Nr="7" P_Summe="0.17" T_Nr="3"/>
    <Posten P_Nr="35" R_Nr="7" P_Summe="1.44" T_Nr="4"/>
    <Posten P_Nr="38" R_Nr="7" P_Summe="4.72" T_Nr="8"/>
    <Posten P_Nr="41" R_Nr="8" P_Summe="1.18" T_Nr="2"/>
    <Posten P_Nr="42" R_Nr="8" P_Summe="0.02" T_Nr="3"/>
    <Posten P_Nr="43" R_Nr="8" P_Summe="1.56" T_Nr="4"/>
    <Posten P_Nr="45" R_Nr="8" P_Summe="0.13" T_Nr="7"/>
    <Posten P_Nr="46" R_Nr="8" P_Summe="2.96" T_Nr="8"/>
    <Posten P_Nr="49" R_Nr="9" P_Summe="1.96" T_Nr="2"/>
    <Posten P_Nr="50" R_Nr="9" P_Summe="1.59" T_Nr="3"/>
    <Posten P_Nr="51" R_Nr="9" P_Summe="1.14" T_Nr="4"/>
    <Posten P_Nr="544" R_Nr="113" P_Summe="1.42" T_Nr="2"/>
    <Posten P_Nr="549" R_Nr="114" P_Summe="3.39" T_Nr="2"/>
    <Posten P_Nr="550" R_Nr="114" P_Summe="1.18" T_Nr="3"/>
    <Posten P_Nr="554" R_Nr="115" P_Summe="5.25" T_Nr="2"/>
    <Posten P_Nr="555" R_Nr="115" P_Summe="1.85" T_Nr="3"/>
    <Posten P_Nr="556" R_Nr="115" P_Summe="1.76" T_Nr="4"/>
    <Posten P_Nr="558" R_Nr="115" P_Summe="2.88" T_Nr="7"/>
    <Posten P_Nr="559" R_Nr="115" P_Summe="4.49" T_Nr="8"/>
    <Posten P_Nr="560" R_Nr="115" P_Summe="2.93" T_Nr="10"/>
  </Postenliste>
  <Tarifliste>
    <Tarif T_Nr="1" T_Name="Frühstück" T_GueBis="30.06.03"/>
    <Tarif T_Nr="2" T_Name="Mittagspause" T_GueBis="30.06.03"/>
    <Tarif T_Nr="3" T_Name="Abendessen" T_GueBis="30.06.03"/>
    <Tarif T_Nr="4" T_Name="Mondschein1" T_GueBis="30.06.03"/>
    <Tarif T_Nr="5" T_Name="Mondschein2" T_GueBis="30.06.03"/>
    <Tarif T_Nr="6" T_Name="Extern" T_GueBis="30.06.03"/>
    <Tarif T_Nr="7" T_Name="Schicht1" T_GueBis="31.12.03"/>
    <Tarif T_Nr="8" T_Name="Schicht2" T_GueBis="31.12.03"/>
    <Tarif T_Nr="9" T_Name="Nachtschicht1" T_GueBis="31.12.03"/>
    <Tarif T_Nr="10" T_Name="Nachtschicht2" T_GueBis="31.12.03"/>
    <Tarif T_Nr="11" T_Name="Extern" T_GueBis="31.12.03"/>
    <Tarif T_Nr="12" T_Name="Frühstück" T_GueBis="31.12.03"/>
    <Tarif T_Nr="13" T_Name="Mittagspause" T_GueBis="31.12.03"/>
    <Tarif T_Nr="14" T_Name="Abendessen" T_GueBis="31.12.03"/>
    <Tarif T_Nr="15" T_Name="Mondschein1" T_GueBis="31.12.03"/>
    <Tarif T_Nr="16" T_Name="Mondschein2" T_GueBis="31.12.03"/>
    <Tarif T_Nr="17" T_Name="Extern" T_GueBis="31.12.03"/>
  </Tarifliste>
</Umsatzliste>
