=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/16_Abfragen/1621_01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2005 sp1 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Posten">
		<xs:complexType>
			<xs:attribute name="P_Nr" type="xs:string" use="required"/>
			<xs:attribute name="R_Nr" type="xs:string" use="required"/>
			<xs:attribute name="P_Summe" type="xs:string" use="required"/>
			<xs:attribute name="T_Nr" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Rechnung">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Posten" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="R_Nr" type="xs:string" use="required"/>
			<xs:attribute name="R_Datum" type="xs:string" use="required"/>
			<xs:attribute name="R_Summe" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Umsatzliste">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Rechnung" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/16_Abfragen/1621_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="1621_02.xslt"?>
<Umsatzliste xmlns:fn="http://www.w3.org/2004/07/xpath-functions" xmlns:xdt="http://www.w3.org/2004/07/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1621_01.xsd">
  <Rechnung R_Nr="7" R_Datum="31.03.03" R_Summe="8.61">
    <Posten P_Nr="33" R_Nr="7" P_Summe="2.28" T_Nr="2"/>
    <Posten P_Nr="34" R_Nr="7" P_Summe="0.17" T_Nr="3"/>
    <Posten P_Nr="35" R_Nr="7" P_Summe="1.44" T_Nr="4"/>
    <Posten P_Nr="38" R_Nr="7" P_Summe="4.72" T_Nr="8"/>
  </Rechnung>
  <Rechnung R_Nr="8" R_Datum="31.03.03" R_Summe="5.85">
    <Posten P_Nr="41" R_Nr="8" P_Summe="1.18" T_Nr="2"/>
    <Posten P_Nr="42" R_Nr="8" P_Summe="0.02" T_Nr="3"/>
    <Posten P_Nr="43" R_Nr="8" P_Summe="1.56" T_Nr="4"/>
    <Posten P_Nr="45" R_Nr="8" P_Summe="0.13" T_Nr="7"/>
    <Posten P_Nr="46" R_Nr="8" P_Summe="2.96" T_Nr="8"/>
  </Rechnung>
  <Rechnung R_Nr="9" R_Datum="31.03.03" R_Summe="4.69">
    <Posten P_Nr="49" R_Nr="9" P_Summe="1.96" T_Nr="2"/>
    <Posten P_Nr="50" R_Nr="9" P_Summe="1.59" T_Nr="3"/>
    <Posten P_Nr="51" R_Nr="9" P_Summe="1.14" T_Nr="4"/>
  </Rechnung>
  <Rechnung R_Nr="113" R_Datum="31.05.03" R_Summe="1.42">
    <Posten P_Nr="544" R_Nr="113" P_Summe="1.42" T_Nr="2"/>
  </Rechnung>
  <Rechnung R_Nr="114" R_Datum="31.05.03" R_Summe="4.57">
    <Posten P_Nr="549" R_Nr="114" P_Summe="3.39" T_Nr="2"/>
    <Posten P_Nr="550" R_Nr="114" P_Summe="1.18" T_Nr="3"/>
  </Rechnung>
  <Rechnung R_Nr="115" R_Datum="31.05.03" R_Summe="19.16">
    <Posten P_Nr="554" R_Nr="115" P_Summe="5.25" T_Nr="2"/>
    <Posten P_Nr="555" R_Nr="115" P_Summe="1.85" T_Nr="3"/>
    <Posten P_Nr="556" R_Nr="115" P_Summe="1.76" T_Nr="4"/>
    <Posten P_Nr="558" R_Nr="115" P_Summe="2.88" T_Nr="7"/>
    <Posten P_Nr="559" R_Nr="115" P_Summe="4.49" T_Nr="8"/>
    <Posten P_Nr="560" R_Nr="115" P_Summe="2.93" T_Nr="10"/>
  </Rechnung>
</Umsatzliste>
