=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/05_Sortierungen/532_05.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2005 U (http://www.xmlspy.com) by Skulschus (Comelio) -->
<!--W3C Schema generated by XMLSpy v2005 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Erfolg">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Stadt" type="xs:string"/>
        <xs:element name="Monat" type="xs:string"/>
        <xs:element ref="Umsatz"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Erfolguebersicht">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Quartal" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Quartal">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Erfolg" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="Nr" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Umsatz">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Gesamt" type="xs:string"/>
        <xs:element name="Neukunden" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/05_Sortierungen/532_05.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="532_05.xslt"?>
<Erfolguebersicht xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="532_05.xsd">
  <Quartal Nr="1">
    <Erfolg>
      <Stadt>Essen, Ruhr</Stadt>
      <Monat>1</Monat>
      <Umsatz>
        <Gesamt>1</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Herne, Westf</Stadt>
      <Monat>1</Monat>
      <Umsatz>
        <Gesamt>2</Gesamt>
        <Neukunden>2</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Duisburg</Stadt>
      <Monat>1</Monat>
      <Umsatz>
        <Gesamt>2</Gesamt>
        <Neukunden>2</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Gelsenkirchen</Stadt>
      <Monat>1</Monat>
      <Umsatz>
        <Gesamt>1</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Düsseldorf</Stadt>
      <Monat>1</Monat>
      <Umsatz>
        <Gesamt>4</Gesamt>
        <Neukunden>4</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Dortmund</Stadt>
      <Monat>2</Monat>
      <Umsatz>
        <Gesamt>2</Gesamt>
        <Neukunden>2</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Duisburg</Stadt>
      <Monat>2</Monat>
      <Umsatz>
        <Gesamt>5</Gesamt>
        <Neukunden>3</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Düsseldorf</Stadt>
      <Monat>2</Monat>
      <Umsatz>
        <Gesamt>17</Gesamt>
        <Neukunden>13</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Bochum</Stadt>
      <Monat>2</Monat>
      <Umsatz>
        <Gesamt>3</Gesamt>
        <Neukunden>3</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Herne, Westf</Stadt>
      <Monat>3</Monat>
      <Umsatz>
        <Gesamt>4</Gesamt>
        <Neukunden>2</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Düsseldorf</Stadt>
      <Monat>3</Monat>
      <Umsatz>
        <Gesamt>33</Gesamt>
        <Neukunden>16</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Duisburg</Stadt>
      <Monat>3</Monat>
      <Umsatz>
        <Gesamt>6</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Bochum</Stadt>
      <Monat>3</Monat>
      <Umsatz>
        <Gesamt>4</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Dortmund</Stadt>
      <Monat>3</Monat>
      <Umsatz>
        <Gesamt>6</Gesamt>
        <Neukunden>4</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Essen, Ruhr</Stadt>
      <Monat>3</Monat>
      <Umsatz>
        <Gesamt>2</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
  </Quartal>
  <Quartal Nr="2">
    <Erfolg>
      <Stadt>Duisburg</Stadt>
      <Monat>4</Monat>
      <Umsatz>
        <Gesamt>7</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Düsseldorf</Stadt>
      <Monat>4</Monat>
      <Umsatz>
        <Gesamt>43</Gesamt>
        <Neukunden>10</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Essen, Ruhr</Stadt>
      <Monat>4</Monat>
      <Umsatz>
        <Gesamt>6</Gesamt>
        <Neukunden>4</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Bochum</Stadt>
      <Monat>4</Monat>
      <Umsatz>
        <Gesamt>9</Gesamt>
        <Neukunden>5</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Dortmund</Stadt>
      <Monat>4</Monat>
      <Umsatz>
        <Gesamt>12</Gesamt>
        <Neukunden>6</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Herne, Westf</Stadt>
      <Monat>4</Monat>
      <Umsatz>
        <Gesamt>9</Gesamt>
        <Neukunden>5</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Bochum</Stadt>
      <Monat>5</Monat>
      <Umsatz>
        <Gesamt>14</Gesamt>
        <Neukunden>5</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Essen, Ruhr</Stadt>
      <Monat>5</Monat>
      <Umsatz>
        <Gesamt>12</Gesamt>
        <Neukunden>6</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Düsseldorf</Stadt>
      <Monat>5</Monat>
      <Umsatz>
        <Gesamt>61</Gesamt>
        <Neukunden>18</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Duisburg</Stadt>
      <Monat>5</Monat>
      <Umsatz>
        <Gesamt>8</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Herne, Westf</Stadt>
      <Monat>5</Monat>
      <Umsatz>
        <Gesamt>12</Gesamt>
        <Neukunden>3</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Dortmund</Stadt>
      <Monat>5</Monat>
      <Umsatz>
        <Gesamt>15</Gesamt>
        <Neukunden>3</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Gelsenkirchen</Stadt>
      <Monat>5</Monat>
      <Umsatz>
        <Gesamt>2</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Gelsenkirchen</Stadt>
      <Monat>6</Monat>
      <Umsatz>
        <Gesamt>5</Gesamt>
        <Neukunden>3</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Duisburg</Stadt>
      <Monat>6</Monat>
      <Umsatz>
        <Gesamt>9</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Dortmund</Stadt>
      <Monat>6</Monat>
      <Umsatz>
        <Gesamt>20</Gesamt>
        <Neukunden>5</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Bochum</Stadt>
      <Monat>6</Monat>
      <Umsatz>
        <Gesamt>15</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Herne, Westf</Stadt>
      <Monat>6</Monat>
      <Umsatz>
        <Gesamt>13</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Essen, Ruhr</Stadt>
      <Monat>6</Monat>
      <Umsatz>
        <Gesamt>17</Gesamt>
        <Neukunden>5</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Düsseldorf</Stadt>
      <Monat>6</Monat>
      <Umsatz>
        <Gesamt>71</Gesamt>
        <Neukunden>10</Neukunden>
      </Umsatz>
    </Erfolg>
  </Quartal>
  <Quartal Nr="3">
    <Erfolg>
      <Stadt>Herne, Westf</Stadt>
      <Monat>7</Monat>
      <Umsatz>
        <Gesamt>15</Gesamt>
        <Neukunden>2</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Düsseldorf</Stadt>
      <Monat>7</Monat>
      <Umsatz>
        <Gesamt>75</Gesamt>
        <Neukunden>4</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Bochum</Stadt>
      <Monat>7</Monat>
      <Umsatz>
        <Gesamt>18</Gesamt>
        <Neukunden>3</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Gelsenkirchen</Stadt>
      <Monat>7</Monat>
      <Umsatz>
        <Gesamt>7</Gesamt>
        <Neukunden>2</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Duisburg</Stadt>
      <Monat>7</Monat>
      <Umsatz>
        <Gesamt>10</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Essen, Ruhr</Stadt>
      <Monat>7</Monat>
      <Umsatz>
        <Gesamt>23</Gesamt>
        <Neukunden>6</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Dortmund</Stadt>
      <Monat>7</Monat>
      <Umsatz>
        <Gesamt>25</Gesamt>
        <Neukunden>5</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Herne, Westf</Stadt>
      <Monat>8</Monat>
      <Umsatz>
        <Gesamt>16</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Essen, Ruhr</Stadt>
      <Monat>8</Monat>
      <Umsatz>
        <Gesamt>27</Gesamt>
        <Neukunden>4</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Bochum</Stadt>
      <Monat>8</Monat>
      <Umsatz>
        <Gesamt>21</Gesamt>
        <Neukunden>3</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Dortmund</Stadt>
      <Monat>8</Monat>
      <Umsatz>
        <Gesamt>26</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Düsseldorf</Stadt>
      <Monat>8</Monat>
      <Umsatz>
        <Gesamt>87</Gesamt>
        <Neukunden>12</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Bochum</Stadt>
      <Monat>9</Monat>
      <Umsatz>
        <Gesamt>22</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Dortmund</Stadt>
      <Monat>9</Monat>
      <Umsatz>
        <Gesamt>41</Gesamt>
        <Neukunden>15</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Duisburg</Stadt>
      <Monat>9</Monat>
      <Umsatz>
        <Gesamt>11</Gesamt>
        <Neukunden>1</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Gelsenkirchen</Stadt>
      <Monat>9</Monat>
      <Umsatz>
        <Gesamt>9</Gesamt>
        <Neukunden>2</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Düsseldorf</Stadt>
      <Monat>9</Monat>
      <Umsatz>
        <Gesamt>97</Gesamt>
        <Neukunden>10</Neukunden>
      </Umsatz>
    </Erfolg>
    <Erfolg>
      <Stadt>Essen, Ruhr</Stadt>
      <Monat>9</Monat>
      <Umsatz>
        <Gesamt>32</Gesamt>
        <Neukunden>5</Neukunden>
      </Umsatz>
    </Erfolg>
  </Quartal>
  <Quartal Nr="4">
    <Erfolg>
      <Stadt>Herne, Westf</Stadt>
