=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/01_Grundkonzept/132_01.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by tester (altova) --><!--W3C Schema generated by XMLSPY v2004 rel. 4 U (http://www.xmlspy.com)--><xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">  <xs:element name="Mitarbeiterliste">    <xs:complexType>      <xs:sequence>        <xs:element name="Mitarbeiter" type="MitarbeiterType" maxOccurs="unbounded"/>      </xs:sequence>    </xs:complexType>  </xs:element>  <xs:complexType name="NameType">    <xs:sequence>      <xs:element name="Vorname" type="xs:string"/>      <xs:element name="Nachname" type="xs:string"/>    </xs:sequence>    <xs:attribute name="Anrede" use="required">      <xs:simpleType>        <xs:restriction base="xs:NMTOKEN">          <xs:enumeration value="Frau"/>          <xs:enumeration value="Herr"/>        </xs:restriction>      </xs:simpleType>    </xs:attribute>  </xs:complexType>  <xs:complexType name="MitarbeiterType">    <xs:sequence>      <xs:element name="Name" type="NameType"/>      <xs:element name="Funktion">        <xs:simpleType>          <xs:restriction base="xs:string">            <xs:enumeration value="Buchhaltung"/>            <xs:enumeration value="Geschäftsführer"/>            <xs:enumeration value="Kundenberater"/>            <xs:enumeration value="Marketing"/>            <xs:enumeration value="Sekretariat"/>            <xs:enumeration value="Technik"/>            <xs:enumeration value="Webseite"/>          </xs:restriction>        </xs:simpleType>      </xs:element>    </xs:sequence>  </xs:complexType></xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/01_Grundkonzept/132_01.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="132_01.xslt"?><Mitarbeiterliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="132_01.xsd">  <Mitarbeiter>    <Name Anrede="Frau">      <Vorname>Birte</Vorname>      <Nachname>Sonnenschein</Nachname>    </Name>    <Funktion>Buchhaltung</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Frau">      <Vorname>Susanne</Vorname>      <Nachname>Rollstein</Nachname>    </Name>    <Funktion>Kundenberater</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Martin</Vorname>      <Nachname>Dünn</Nachname>    </Name>    <Funktion>Kundenberater</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Holger</Vorname>      <Nachname>Schnellschuss</Nachname>    </Name>    <Funktion>Sekretariat</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Stefan</Vorname>      <Nachname>Erdbau</Nachname>    </Name>    <Funktion>Sekretariat</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Ralf</Vorname>      <Nachname>Hostell</Nachname>    </Name>    <Funktion>Sekretariat</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Lars</Vorname>      <Nachname>Klapp</Nachname>    </Name>    <Funktion>Kundenberater</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Frau">      <Vorname>Anja</Vorname>      <Nachname>Doppelt</Nachname>    </Name>    <Funktion>Technik</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Reinhard</Vorname>      <Nachname>Bergluft</Nachname>    </Name>    <Funktion>Technik</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Marco</Vorname>      <Nachname>Scheffchen</Nachname>    </Name>    <Funktion>Geschäftsführer</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Frau">      <Vorname>Marcus</Vorname>      <Nachname>Bodensee</Nachname>    </Name>    <Funktion>Geschäftsführer</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Dirk</Vorname>      <Nachname>Still</Nachname>    </Name>    <Funktion>Technik</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Markus</Vorname>      <Nachname>Bärchen</Nachname>    </Name>    <Funktion>Buchhaltung</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Nils</Vorname>      <Nachname>Latz</Nachname>    </Name>    <Funktion>Buchhaltung</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Frau">      <Vorname>Kristina</Vorname>      <Nachname>Gelddreh</Nachname>    </Name>    <Funktion>Marketing</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Markus</Vorname>      <Nachname>Feder</Nachname>    </Name>    <Funktion>Webseite</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Thomas</Vorname>      <Nachname>Gold</Nachname>    </Name>    <Funktion>Marketing</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Mischa</Vorname>      <Nachname>Fingerflink</Nachname>    </Name>    <Funktion>Kundenberater</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Christian</Vorname>      <Nachname>Ordinarius</Nachname>    </Name>    <Funktion>Kundenberater</Funktion>  </Mitarbeiter>  <Mitarbeiter>    <Name Anrede="Herr">      <Vorname>Anton</Vorname>      <Nachname>Ebenhof</Nachname>    </Name>    <Funktion>Kundenberater</Funktion>  </Mitarbeiter></Mitarbeiterliste>
