=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/02_Vorlagen/222_01.xsd
<?xml version="1.0" encoding="ISO-8859-1"?><!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by tester (altova) --><!--W3C Schema generated by XMLSPY v2004 rel. 4 U (http://www.xmlspy.com)--><xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">  <xs:element name="Anrufliste">    <xs:complexType>      <xs:sequence>        <xs:element name="Anruf" maxOccurs="unbounded">          <xs:complexType>            <xs:sequence>              <xs:element name="Beginn" type="xs:string"/>              <xs:element name="Dauer" type="xs:byte"/>              <xs:element name="Preis" type="xs:byte"/>              <xs:element name="Tarif">                <xs:complexType>                  <xs:simpleContent>                    <xs:extension base="xs:string">                      <xs:attribute name="Nr" type="xs:byte" use="required"/>                    </xs:extension>                  </xs:simpleContent>                </xs:complexType>              </xs:element>              <!-- Element Von -->              <xs:element name="Von">                <xs:complexType>                  <xs:sequence>                    <xs:element ref="Name"/>                    <xs:element ref="Stadt"/>                  </xs:sequence>                  <xs:attribute name="Nr" type="xs:byte" use="required"/>                </xs:complexType>              </xs:element>              <!-- Element Nach -->              <xs:element name="Nach">                <xs:complexType>                  <xs:sequence>                    <xs:element ref="Name"/>                    <xs:element ref="Stadt"/>                  </xs:sequence>                  <xs:attribute name="Nr" type="xs:byte" use="required"/>                </xs:complexType>              </xs:element>            </xs:sequence>            <xs:attribute name="Nr" type="xs:short" use="required"/>            <xs:attribute name="Typ" type="xs:string" use="required"/>          </xs:complexType>        </xs:element>      </xs:sequence>    </xs:complexType>  </xs:element>    <!-- Globale Elemente -->  <xs:element name="Name" type="xs:string"/>  <xs:element name="Stadt" type="xs:string"/></xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/02_Vorlagen/222_01.xml
<?xml version="1.0" encoding="ISO-8859-1"?><?xml-stylesheet type="text/xsl" href="222_01.xslt"?><Anrufliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="222_01.xsd"><!-- FGL Seite 87ff: Hier wird eine andere xsd Datei angepriesen, aktuell wird aber eine mit nicht so guter Modellierung genutzt -->  <Anruf Nr="4897" Typ="p">    <Beginn>21.06.03 05:06:00</Beginn>    <Dauer>81</Dauer>    <Preis>41</Preis>    <Tarif Nr="5">Mondschein2</Tarif>    <Von Nr="36">      <Name>Cebula, Peter</Name>      <Stadt>Dortmund</Stadt>    </Von>    <Nach Nr="46">      <Name>Brauner, Dieter</Name>      <Stadt>Düsseldorf</Stadt>    </Nach>  </Anruf>  <Anruf Nr="4899" Typ="p">    <Beginn>21.06.03 08:06:00</Beginn>    <Dauer>39</Dauer>    <Preis>20</Preis>    <Tarif Nr="1">Frühstück</Tarif>    <Von Nr="39">      <Name>Riecks, Gisela</Name>      <Stadt>Dortmund</Stadt>    </Von>    <Nach Nr="116">      <Name>Stielow, Wadim</Name>      <Stadt>Herne, Westf</Stadt>    </Nach>  </Anruf>  <Anruf Nr="4828" Typ="p">    <Beginn>20.06.03 08:06:00</Beginn>    <Dauer>8</Dauer>    <Preis>4</Preis>    <Tarif Nr="4">Mondschein1</Tarif>    <Von Nr="122">      <Name>Gebhard, Manfred</Name>      <Stadt>Düsseldorf</Stadt>    </Von>    <Nach Nr="76">      <Name>Besl, Heinz</Name>      <Stadt>Düsseldorf</Stadt>    </Nach>  </Anruf>  <Anruf Nr="4871" Typ="g">    <Beginn>20.06.03 08:06:00</Beginn>    <Dauer>110</Dauer>    <Preis>55</Preis>    <Tarif Nr="7">Schicht1</Tarif>    <Von Nr="22">      <Name>KS Kühl-System- GmbH + Co</Name>      <Stadt>Bochum</Stadt>    </Von>    <Nach Nr="25">      <Name>Küchenstudio Mittelauer GmbH</Name>      <Stadt>Essen, Ruhr</Stadt>    </Nach>  </Anruf>  <Anruf Nr="4880" Typ="g">    <Beginn>20.06.03 09:06:00</Beginn>    <Dauer>4</Dauer>    <Preis>2</Preis>    <Tarif Nr="7">Schicht1</Tarif>    <Von Nr="29">      <Name>König Hof Weinkellerei GmbH</Name>      <Stadt>Duisburg</Stadt>    </Von>    <Nach Nr="7">      <Name>ELMO Elektro Mommse GmbH</Name>      <Stadt>Gelsenkirchen</Stadt>    </Nach>  </Anruf></Anrufliste>
