=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/12_EigeneFunktionen/1212_01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Bis" type="xs:string"/>
  <xs:element name="Durchschnitt" type="xs:string"/>
  <xs:element name="Gueltigkeit">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Von"/>
        <xs:element ref="Bis"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Kunden" type="xs:string"/>
  <xs:element name="Name">
    <xs:complexType mixed="true">
      <xs:attribute name="Nr" type="xs:string" use="required"/>
      <xs:attribute name="Typ" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Preis" type="xs:string"/>
  <xs:element name="Summe" type="xs:string"/>
  <xs:element name="Tarif">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="Gueltigkeit"/>
        <xs:element ref="Uhrzeit"/>
        <xs:element ref="Preis"/>
        <xs:element ref="Umsatz"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Tarifliste">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Tarif" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Uhrzeit">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Von"/>
        <xs:element ref="Bis"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Umsatz">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Summe"/>
        <xs:element ref="Kunden"/>
        <xs:element ref="Durchschnitt"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Von" type="xs:string"/>
</xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/12_EigeneFunktionen/1212_01.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="232_01.xslt"?>
<Tarifliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1212_01.xsd">
  <Tarif>
    <Name Nr="7" Typ="g">Schicht1</Name>
    <Gueltigkeit>
      <Von>01.01.03</Von>
      <Bis>31.12.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>7</Von>
      <Bis>15</Bis>
    </Uhrzeit>
    <Preis/>
    <Umsatz>
      <Summe>2.313,50</Summe>
      <Kunden>787</Kunden>
      <Durchschnitt>2,94</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="18" Typ="g">Schicht1</Name>
    <Gueltigkeit>
      <Von>01.01.04</Von>
      <Bis>31.12.04</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>7</Von>
      <Bis>15</Bis>
    </Uhrzeit>
    <Preis>1</Preis>
    <Umsatz>
      <Summe>75.287,52</Summe>
      <Kunden>4352</Kunden>
      <Durchschnitt>17,30</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="8" Typ="g">Schicht2</Name>
    <Gueltigkeit>
      <Von>01.01.03</Von>
      <Bis>31.12.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>15</Von>
      <Bis>23</Bis>
    </Uhrzeit>
    <Preis>1</Preis>
    <Umsatz>
      <Summe>5.250,29</Summe>
      <Kunden>797</Kunden>
      <Durchschnitt>6,59</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="19" Typ="g">Schicht2</Name>
    <Gueltigkeit>
      <Von>01.01.04</Von>
      <Bis>31.12.04</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>15</Von>
      <Bis>23</Bis>
    </Uhrzeit>
    <Preis>15</Preis>
    <Umsatz>
      <Summe>130.502,08</Summe>
      <Kunden>4356</Kunden>
      <Durchschnitt>29,96</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="1" Typ="p">Frühstück</Name>
    <Gueltigkeit>
      <Von>01.01.03</Von>
      <Bis>30.06.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>6</Von>
      <Bis>10</Bis>
    </Uhrzeit>
    <Preis/>
    <Umsatz>
      <Summe>57,68</Summe>
      <Kunden>2233</Kunden>
      <Durchschnitt>,03</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="12" Typ="p">Frühstück</Name>
    <Gueltigkeit>
      <Von>01.07.03</Von>
      <Bis>31.12.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>6</Von>
      <Bis>10</Bis>
    </Uhrzeit>
    <Preis>1</Preis>
    <Umsatz>
      <Summe>1.829,45</Summe>
      <Kunden>1158</Kunden>
      <Durchschnitt>1,58</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="23" Typ="p">Frühstück</Name>
    <Gueltigkeit>
      <Von>01.01.04</Von>
      <Bis>31.12.04</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>6</Von>
      <Bis>10</Bis>
    </Uhrzeit>
    <Preis>1</Preis>
    <Umsatz>
      <Summe>29.939,16</Summe>
      <Kunden>11941</Kunden>
      <Durchschnitt>2,51</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="3" Typ="p">Abendessen</Name>
    <Gueltigkeit>
      <Von>01.01.03</Von>
      <Bis>30.06.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>15</Von>
      <Bis>20</Bis>
    </Uhrzeit>
    <Preis>1</Preis>
    <Umsatz>
      <Summe>317,73</Summe>
      <Kunden>185</Kunden>
      <Durchschnitt>1,72</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="14" Typ="p">Abendessen</Name>
    <Gueltigkeit>
      <Von>01.07.03</Von>
      <Bis>31.12.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>15</Von>
      <Bis>20</Bis>
    </Uhrzeit>
    <Preis>15</Preis>
    <Umsatz>
      <Summe>4.768,57</Summe>
      <Kunden>1174</Kunden>
      <Durchschnitt>4,06</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="25" Typ="p">Abendessen</Name>
    <Gueltigkeit>
      <Von>01.01.04</Von>
      <Bis>31.12.04</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>15</Von>
      <Bis>24</Bis>
    </Uhrzeit>
    <Preis>1</Preis>
    <Umsatz>
      <Summe>77.214,42</Summe>
      <Kunden>12049</Kunden>
      <Durchschnitt>6,41</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="4" Typ="p">Mondschein1</Name>
    <Gueltigkeit>
      <Von>01.01.03</Von>
      <Bis>30.06.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>20</Von>
      <Bis>24</Bis>
    </Uhrzeit>
    <Preis/>
    <Umsatz>
      <Summe>58,98</Summe>
      <Kunden>175</Kunden>
      <Durchschnitt>,34</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="15" Typ="p">Mondschein1</Name>
    <Gueltigkeit>
      <Von>01.07.03</Von>
      <Bis>31.12.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>20</Von>
      <Bis>24</Bis>
    </Uhrzeit>
    <Preis/>
    <Umsatz>
      <Summe>689,67</Summe>
      <Kunden>1146</Kunden>
      <Durchschnitt>,60</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="26" Typ="p">Mondschein1</Name>
    <Gueltigkeit>
      <Von>01.01.04</Von>
      <Bis>31.12.04</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>0</Von>
      <Bis>6</Bis>
    </Uhrzeit>
    <Preis/>
    <Umsatz>
      <Summe>28.363,22</Summe>
      <Kunden>12008</Kunden>
      <Durchschnitt>2,36</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="5" Typ="p">Mondschein2</Name>
    <Gueltigkeit>
      <Von>01.01.03</Von>
      <Bis>30.06.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>0</Von>
      <Bis>6</Bis>
    </Uhrzeit>
    <Preis/>
    <Umsatz>
      <Summe>178,12</Summe>
      <Kunden>183</Kunden>
      <Durchschnitt>,97</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="16" Typ="p">Mondschein2</Name>
    <Gueltigkeit>
      <Von>01.07.03</Von>
      <Bis>31.12.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>0</Von>
      <Bis>6</Bis>
    </Uhrzeit>
    <Preis/>
    <Umsatz>
      <Summe>1.679,86</Summe>
      <Kunden>1179</Kunden>
      <Durchschnitt>1,42</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="2" Typ="p">Mittagspause</Name>
    <Gueltigkeit>
      <Von>01.01.03</Von>
      <Bis>30.06.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>10</Von>
      <Bis>15</Bis>
    </Uhrzeit>
    <Preis>1</Preis>
    <Umsatz>
      <Summe>347,97</Summe>
      <Kunden>184</Kunden>
      <Durchschnitt>1,89</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="13" Typ="p">Mittagspause</Name>
    <Gueltigkeit>
      <Von>01.07.03</Von>
      <Bis>31.12.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>10</Von>
      <Bis>15</Bis>
    </Uhrzeit>
    <Preis>15</Preis>
    <Umsatz>
      <Summe>4.507,92</Summe>
      <Kunden>1168</Kunden>
      <Durchschnitt>3,86</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="24" Typ="p">Mittagspause</Name>
    <Gueltigkeit>
      <Von>01.01.04</Von>
      <Bis>31.12.04</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>10</Von>
      <Bis>15</Bis>
    </Uhrzeit>
    <Preis>15</Preis>
    <Umsatz>
      <Summe>70.978,92</Summe>
      <Kunden>11995</Kunden>
      <Durchschnitt>5,92</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="10" Typ="g">Nachtschicht2</Name>
    <Gueltigkeit>
      <Von>01.01.03</Von>
      <Bis>31.12.03</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>0</Von>
      <Bis>7</Bis>
    </Uhrzeit>
    <Preis/>
    <Umsatz>
      <Summe>2.234,03</Summe>
      <Kunden>788</Kunden>
      <Durchschnitt>2,84</Durchschnitt>
    </Umsatz>
  </Tarif>
  <Tarif>
    <Name Nr="21" Typ="g">Nachtschicht2</Name>
    <Gueltigkeit>
      <Von>01.01.04</Von>
      <Bis>31.12.04</Bis>
    </Gueltigkeit>
    <Uhrzeit>
      <Von>0</Von>
      <Bis>7</Bis>
    </Uhrzeit>
    <Preis>1</Preis>
    <Umsatz>
      <Summe>71.129,51</Summe>
      <Kunden>4354</Kunden>
      <Durchschnitt>16,34</Durchschnitt>
    </Umsatz>
  </Tarif>
</Tarifliste>
