=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/13_XMLSchema/1312_01.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:simpleType name="Waehrung">
    <xs:restriction base="xs:decimal">
      <xs:totalDigits value="10"/>
      <xs:fractionDigits value="2"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="UmsatzTyp">
    <xs:sequence>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="Umsatz" type="Waehrung"/>
      <xs:element name="Anrufe" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StadtTyp">
    <xs:sequence>
      <xs:element name="Name"/>
      <xs:element name="Zahl"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Umsatzuebersicht">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Stadtliste" type="StadtlisteTyp"/>
        <xs:element name="Tarifliste">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Privat">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Tarif" type="UmsatzTyp" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Geschaeftlich">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Tarif" type="UmsatzTyp" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Kundenliste">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Privat">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="Stadt" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Geschaeftlich">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="Stadt" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Datum" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Stadt" type="StadtTyp"/>
  <xs:complexType name="StadtlisteTyp">
    <xs:sequence>
      <xs:element name="Privat">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Stadt" type="UmsatzTyp" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Geschaeftlich">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Stadt" type="UmsatzTyp" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/13_XMLSchema/1312_01.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="1312_01.xslt"?>
<Umsatzuebersicht xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1312_01.xsd" Datum="2004-12-31">
  <Stadtliste>
    <Privat>
      <Stadt>
        <Name>Bochum</Name>
        <Umsatz>20232.96</Umsatz>
        <Anrufe>57813</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Düsseldorf</Name>
        <Umsatz>70567.68</Umsatz>
        <Anrufe>201369</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Dortmund</Name>
        <Umsatz>33435.45</Umsatz>
        <Anrufe>95428</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Duisburg</Name>
        <Umsatz>23128.01</Umsatz>
        <Anrufe>66721</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Essen. Ruhr</Name>
        <Umsatz>34966.51</Umsatz>
        <Anrufe>99860</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Gelsenkirchen</Name>
        <Umsatz>10351.78</Umsatz>
        <Anrufe>29275</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Herne. Westf</Name>
        <Umsatz>8740.66</Umsatz>
        <Anrufe>24638</Anrufe>
      </Stadt>
    </Privat>
    <Geschaeftlich>
      <Stadt>
        <Name>Bochum</Name>
        <Umsatz>12645.78</Umsatz>
        <Anrufe>30219</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Düsseldorf</Name>
        <Umsatz>58552.62</Umsatz>
        <Anrufe>143330</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Dortmund</Name>
        <Umsatz>28886.78</Umsatz>
        <Anrufe>69742</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Duisburg</Name>
        <Umsatz>20601.99</Umsatz>
        <Anrufe>50764</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Essen. Ruhr</Name>
        <Umsatz>28814.24</Umsatz>
        <Anrufe>68776</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Gelsenkirchen</Name>
        <Umsatz>7560.45</Umsatz>
        <Anrufe>18430</Anrufe>
      </Stadt>
      <Stadt>
        <Name>Herne. Westf</Name>
        <Umsatz>4745.8</Umsatz>
        <Anrufe>11746</Anrufe>
      </Stadt>
    </Geschaeftlich>
  </Stadtliste>
  <Tarifliste>
    <Privat>
      <Tarif>
        <Name>Abendessen</Name>
        <Umsatz>74505.9</Umsatz>
        <Anrufe>200055</Anrufe>
      </Tarif>
      <Tarif>
        <Name>Frühstück</Name>
        <Umsatz>29492.04</Umsatz>
        <Anrufe>97070</Anrufe>
      </Tarif>
      <Tarif>
        <Name>Mittagspause</Name>
        <Umsatz>68668.9</Umsatz>
        <Anrufe>123751</Anrufe>
      </Tarif>
      <Tarif>
        <Name>Mondschein1</Name>
        <Umsatz>26973.55</Umsatz>
        <Anrufe>144626</Anrufe>
      </Tarif>
      <Tarif>
        <Name>Mondschein2</Name>
        <Umsatz>1782.66</Umsatz>
        <Anrufe>9602</Anrufe>
      </Tarif>
    </Privat>
    <Geschaeftlich>
      <Tarif>
        <Name>Frühstück</Name>
        <Umsatz>0</Umsatz>
        <Anrufe>2966</Anrufe>
      </Tarif>
      <Tarif>
        <Name>Nachtschicht2</Name>
        <Umsatz>41653.11</Umsatz>
        <Anrufe>119692</Anrufe>
      </Tarif>
      <Tarif>
        <Name>Schicht1</Name>
        <Umsatz>44023.75</Umsatz>
        <Anrufe>130239</Anrufe>
      </Tarif>
      <Tarif>
        <Name>Schicht2</Name>
        <Umsatz>76130.8</Umsatz>
        <Anrufe>140110</Anrufe>
      </Tarif>
    </Geschaeftlich>
  </Tarifliste>
  <Kundenliste>
    <Privat>
      <Stadt>
        <Name>Bochum</Name>
        <Zahl>153</Zahl>
      </Stadt>
      <Stadt>
        <Name>D?sseldorf</Name>
        <Zahl>506</Zahl>
      </Stadt>
      <Stadt>
        <Name>Dortmund</Name>
        <Zahl>225</Zahl>
      </Stadt>
      <Stadt>
        <Name>Duisburg</Name>
        <Zahl>196</Zahl>
      </Stadt>
      <Stadt>
        <Name>Essen, Ruhr</Name>
        <Zahl>233</Zahl>
      </Stadt>
      <Stadt>
        <Name>Gelsenkirchen</Name>
        <Zahl>70</Zahl>
      </Stadt>
      <Stadt>
        <Name>Herne, Westf</Name>
        <Zahl>64</Zahl>
      </Stadt>
    </Privat>
    <Geschaeftlich>
      <Stadt>
        <Name>Bochum</Name>
        <Zahl>32</Zahl>
      </Stadt>
      <Stadt>
        <Name>Dortmund</Name>
        <Zahl>64</Zahl>
      </Stadt>
      <Stadt>
        <Name>Duisburg</Name>
        <Zahl>37</Zahl>
      </Stadt>
      <Stadt>
        <Name>Düsseldorf</Name>
        <Zahl>62</Zahl>
      </Stadt>
      <Stadt>
        <Name>Essen, Ruhr</Name>
        <Zahl>43</Zahl>
      </Stadt>
      <Stadt>
        <Name>Gelsenkirchen</Name>
        <Zahl>23</Zahl>
      </Stadt>
      <Stadt>
        <Name>Herne, Westf</Name>
        <Zahl>8</Zahl>
      </Stadt>
    </Geschaeftlich>
  </Kundenliste>
</Umsatzuebersicht>
