=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/14_XPathFunktionen/1411_01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2005 sp1 U (http://www.xmlspy.com) by Skulschus (Comelio) -->
<!--W3C Schema generated by XMLSpy v2005 sp1 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Adresse">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Strasse"/>
        <xs:element ref="PLZ"/>
        <xs:element ref="Stadt"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Einzeln" type="xs:decimal"/>
  <xs:element name="Kunde">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="Adresse"/>
      </xs:sequence>
      <xs:attribute name="Typ" type="xs:string" use="required"/>
      <xs:attribute name="Nr" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Nachname" type="xs:string"/>
  <xs:element name="Name">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Vorname"/>
        <xs:element ref="Nachname"/>
      </xs:sequence>
      <xs:attribute name="Anrede" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PLZ" type="xs:string"/>
  <xs:element name="Posten">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Tarif"/>
        <xs:element ref="Einzeln"/>
      </xs:sequence>
      <xs:attribute name="Nr" type="xs:string" use="required"/>
      <xs:attribute name="RefNr" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Postenliste">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Posten" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Rechnung">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Total"/>
        <xs:element ref="Kunde"/>
        <xs:element ref="Postenliste"/>
      </xs:sequence>
      <xs:attribute name="Nr" type="xs:string" use="required"/>
      <xs:attribute name="Datum" type="xs:date" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Rechnungen">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Rechnung" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Stadt" type="xs:string"/>
  <xs:element name="Strasse" type="xs:string"/>
  <xs:element name="Tarif" type="xs:string"/>
  <xs:element name="Total" type="xs:decimal"/>
  <xs:element name="Vorname" type="xs:string"/>
</xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/14_XPathFunktionen/1421_01.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="422_01.xslt"?>
<Rechnungen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1411_01.xsd">
  <Rechnung Nr="12212" Datum="2004-12-31">
    <Total>26.59</Total>
    <Kunde Typ="p" Nr="145">
      <Name Anrede="Herr">
        <Vorname>Ralf        </Vorname>
        <Nachname>Gajewski        </Nachname>
      </Name>
      <Adresse>
        <Strasse>Hohenzollernstr. 30</Strasse>
        <PLZ>40211</PLZ>
        <Stadt>Düsseldorf</Stadt>
      </Adresse>
    </Kunde>
    <Postenliste>
      <Posten Nr="63084" RefNr="12212">
        <Tarif>Frühstück</Tarif>
        <Einzeln>3.76</Einzeln>
      </Posten>
      <Posten Nr="63085" RefNr="12212">
        <Tarif>Mittagspause</Tarif>
        <Einzeln>10.11</Einzeln>
      </Posten>
      <Posten Nr="63086" RefNr="12212">
        <Tarif>Abendessen</Tarif>
        <Einzeln>8.78</Einzeln>
      </Posten>
      <Posten Nr="63087" RefNr="12212">
        <Tarif>Mondschein1</Tarif>
        <Einzeln>3.94</Einzeln>
      </Posten>
    </Postenliste>
  </Rechnung>
  <Rechnung Nr="12717" Datum="2004-12-31">
    <Total>18.31</Total>
    <Kunde Typ="p" Nr="653">
      <Name Anrede="Herr">
        <Vorname>Martin        </Vorname>
        <Nachname>Ploger        </Nachname>
      </Name>
      <Adresse>
        <Strasse/>
        <PLZ>0</PLZ>
        <Stadt>Dortmund</Stadt>
      </Adresse>
    </Kunde>
    <Postenliste>
      <Posten Nr="66155" RefNr="12717">
        <Tarif>Frühstück</Tarif>
        <Einzeln>2.51</Einzeln>
      </Posten>
      <Posten Nr="66156" RefNr="12717">
        <Tarif>Mittagspause</Tarif>
        <Einzeln>4.71</Einzeln>
      </Posten>
      <Posten Nr="66157" RefNr="12717">
        <Tarif>Abendessen</Tarif>
        <Einzeln>8.95</Einzeln>
      </Posten>
      <Posten Nr="66158" RefNr="12717">
        <Tarif>Mondschein1</Tarif>
        <Einzeln>2.14</Einzeln>
      </Posten>
    </Postenliste>
  </Rechnung>
  <Rechnung Nr="12849" Datum="2004-12-31">
    <Total>2.24</Total>
    <Kunde Typ="p" Nr="786">
      <Name Anrede="Herr">
        <Vorname>Markus        </Vorname>
        <Nachname>Glowatsch        </Nachname>
      </Name>
      <Adresse>
        <Strasse>Holbeinstr. 3</Strasse>
        <PLZ>40237</PLZ>
        <Stadt>Düsseldorf</Stadt>
      </Adresse>
    </Kunde>
    <Postenliste>
      <Posten Nr="66811" RefNr="12849">
        <Tarif>Frühstück</Tarif>
        <Einzeln>2.96</Einzeln>
      </Posten>
      <Posten Nr="66814" RefNr="12849">
        <Tarif>Mondschein1</Tarif>
        <Einzeln>3.21</Einzeln>
      </Posten>
      <Posten Nr="66812" RefNr="12849">
        <Tarif>Mittagspause</Tarif>
        <Einzeln>8.97</Einzeln>
      </Posten>
      <Posten Nr="66813" RefNr="12849">
        <Tarif>Abendessen</Tarif>
        <Einzeln>7.26</Einzeln>
      </Posten>
    </Postenliste>
  </Rechnung>
  <Rechnung Nr="12941" Datum="2004-12-31">
    <Total>24.98</Total>
    <Kunde Typ="p" Nr="879">
      <Name Anrede="Herr">
        <Vorname>Anton        </Vorname>
        <Nachname>Cirkel        </Nachname>
      </Name>
      <Adresse>
        <Strasse>Theodor-Otte-Str. 50</Strasse>
        <PLZ>45897</PLZ>
        <Stadt>Gelsenkirchen</Stadt>
      </Adresse>
    </Kunde>
    <Postenliste>
      <Posten Nr="67269" RefNr="12941">
        <Tarif>Frühstück</Tarif>
        <Einzeln>4.06</Einzeln>
      </Posten>
      <Posten Nr="67271" RefNr="12941">
        <Tarif>Abendessen</Tarif>
        <Einzeln>9.66</Einzeln>
      </Posten>
      <Posten Nr="67270" RefNr="12941">
        <Tarif>Mittagspause</Tarif>
        <Einzeln>8.01</Einzeln>
      </Posten>
      <Posten Nr="67272" RefNr="12941">
        <Tarif>Mondschein1</Tarif>
        <Einzeln>3.25</Einzeln>
      </Posten>
    </Postenliste>
  </Rechnung>
</Rechnungen>
