=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/14_XPathFunktionen/1431_01.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2005 sp1 U (http://www.xmlspy.com)-->
<!ELEMENT Adresse (Strasse, PLZ, Stadt)>
<!ELEMENT Einzeln (#PCDATA)>
<!ELEMENT Kunde (Name, Adresse)>
<!ATTLIST Kunde
	Typ CDATA #REQUIRED
	Nr CDATA #REQUIRED
>
<!ELEMENT Nachname (#PCDATA)>
<!ELEMENT Name (Vorname, Nachname)>
<!ATTLIST Name
	xml:lang CDATA #REQUIRED
	Anrede CDATA #REQUIRED
>
<!ELEMENT PLZ (#PCDATA)>
<!ELEMENT Posten (Tarif, Einzeln)>
<!ATTLIST Posten
	Nr CDATA #REQUIRED
	RefNr CDATA #REQUIRED
>
<!ELEMENT Postenliste (Posten+)>
<!ELEMENT Rechnung (Total, Kunde, Postenliste)>
<!ATTLIST Rechnung
	Nr CDATA #REQUIRED
	Datum CDATA #REQUIRED
>
<!ELEMENT Rechnungen (Rechnung+)>
<!ATTLIST Rechnungen
	xmlns:xsi CDATA #IMPLIED
	xsi:noNamespaceSchemaLocation CDATA #IMPLIED
>
<!ELEMENT Stadt (#PCDATA)>
<!ELEMENT Strasse (#PCDATA)>
<!ELEMENT Tarif (#PCDATA)>
<!ATTLIST Tarif
	xml:lang CDATA #REQUIRED
>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Vorname (#PCDATA)>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/14_XPathFunktionen/1431_01.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Rechnungen SYSTEM "1431_01.dtd">
<?xml-stylesheet type="text/xsl" href="1432_01.xslt"?>
<Rechnungen>
  <Rechnung Nr="12212" Datum="2004-12-31">
    <Total>26.59</Total>
    <Kunde Typ="p" Nr="145">
      <Name xml:lang="de" Anrede="Herr">
        <Vorname>Ralf</Vorname>
        <Nachname>Gajewski</Nachname>
      </Name>
      <Adresse>
        <Strasse>Hohenzollernstr. 30</Strasse>
        <PLZ>40211</PLZ>
        <Stadt>Düsseldorf</Stadt>
      </Adresse>
    </Kunde>
    <Postenliste>
      <Posten Nr="63084" RefNr="12212">
        <Tarif xml:lang="de">Frühstück</Tarif>
        <Einzeln>3.76</Einzeln>
      </Posten>
      <Posten Nr="63085" RefNr="12212">
        <Tarif xml:lang="de">Mittagspause</Tarif>
        <Einzeln>10.11</Einzeln>
      </Posten>
      <Posten Nr="63086" RefNr="12212">
        <Tarif xml:lang="de">Abendessen</Tarif>
        <Einzeln>8.78</Einzeln>
      </Posten>
      <Posten Nr="63087" RefNr="12212">
        <Tarif xml:lang="de">Mondschein1</Tarif>
        <Einzeln>3.94</Einzeln>
      </Posten>
    </Postenliste>
  </Rechnung>
  <Rechnung Nr="12717" Datum="2004-12-31">
    <Total>18.31</Total>
    <Kunde Typ="p" Nr="653">
      <Name xml:lang="de" Anrede="Herr">
        <Vorname>Martin</Vorname>
        <Nachname>Ploger</Nachname>
      </Name>
      <Adresse>
        <Strasse/>
        <PLZ>0</PLZ>
        <Stadt>Dortmund</Stadt>
      </Adresse>
    </Kunde>
    <Postenliste>
      <Posten Nr="66155" RefNr="12717">
        <Tarif xml:lang="de">Frühstück</Tarif>
        <Einzeln>2.51</Einzeln>
      </Posten>
      <Posten Nr="66156" RefNr="12717">
        <Tarif xml:lang="de">Mittagspause</Tarif>
        <Einzeln>4.71</Einzeln>
      </Posten>
      <Posten Nr="66157" RefNr="12717">
        <Tarif xml:lang="de">Abendessen</Tarif>
        <Einzeln>8.95</Einzeln>
      </Posten>
      <Posten Nr="66158" RefNr="12717">
        <Tarif xml:lang="de">Mondschein1</Tarif>
        <Einzeln>2.14</Einzeln>
      </Posten>
    </Postenliste>
  </Rechnung>
  <Rechnung Nr="12849" Datum="2004-12-31">
    <Total>2.24</Total>
    <Kunde Typ="p" Nr="786">
      <Name xml:lang="de" Anrede="Herr">
        <Vorname>Markus</Vorname>
        <Nachname>Glowatsch</Nachname>
      </Name>
      <Adresse>
        <Strasse>Holbeinstr. 3</Strasse>
        <PLZ>40237</PLZ>
        <Stadt>Düsseldorf</Stadt>
      </Adresse>
    </Kunde>
    <Postenliste>
      <Posten Nr="66811" RefNr="12849">
        <Tarif xml:lang="de">Frühstück</Tarif>
        <Einzeln>2.96</Einzeln>
      </Posten>
      <Posten Nr="66814" RefNr="12849">
        <Tarif xml:lang="de">Mondschein1</Tarif>
        <Einzeln>3.21</Einzeln>
      </Posten>
      <Posten Nr="66812" RefNr="12849">
        <Tarif xml:lang="de">Mittagspause</Tarif>
        <Einzeln>8.97</Einzeln>
      </Posten>
      <Posten Nr="66813" RefNr="12849">
        <Tarif xml:lang="de">Abendessen</Tarif>
        <Einzeln>7.26</Einzeln>
      </Posten>
    </Postenliste>
  </Rechnung>
  <Rechnung Nr="12941" Datum="2004-12-31">
    <Total>24.98</Total>
    <Kunde Typ="p" Nr="879">
      <Name xml:lang="de" Anrede="Herr">
        <Vorname>Anton</Vorname>
        <Nachname>Cirkel</Nachname>
      </Name>
      <Adresse>
        <Strasse>Theodor-Otte-Str. 50</Strasse>
        <PLZ>45897</PLZ>
        <Stadt>Gelsenkirchen</Stadt>
      </Adresse>
    </Kunde>
    <Postenliste>
      <Posten Nr="67269" RefNr="12941">
        <Tarif xml:lang="de">Frühstück</Tarif>
        <Einzeln>4.06</Einzeln>
      </Posten>
      <Posten Nr="67271" RefNr="12941">
        <Tarif xml:lang="de">Abendessen</Tarif>
        <Einzeln>9.66</Einzeln>
      </Posten>
      <Posten Nr="67270" RefNr="12941">
        <Tarif xml:lang="de">Mittagspause</Tarif>
        <Einzeln>8.01</Einzeln>
      </Posten>
      <Posten Nr="67272" RefNr="12941">
        <Tarif xml:lang="de">Mondschein1</Tarif>
        <Einzeln>3.25</Einzeln>
      </Posten>
    </Postenliste>
  </Rechnung>
</Rechnungen>
