=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/14_XPathFunktionen/1441_01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2005 sp1 U (http://www.xmlspy.com) by Skulschus (Comelio) -->
<!--W3C Schema generated by XMLSpy v2005 sp1 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Beginn" type="xs:dateTime"/>
  <xs:element name="Dauer" type="xs:integer"/>
  <xs:element name="Stadt" type="xs:string"/>
  <xs:element name="Umsatz">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="Stadt"/>
        <xs:element ref="Beginn"/>
        <xs:element ref="Dauer"/>
        <xs:element name="Umsatz" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Umsatz-Pro-Stadt">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="Umsatz" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/14_XPathFunktionen/1441_02.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="1442_01.xslt"?>
<Umsatz-Pro-Stadt xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2004/07/xpath-functions" xmlns:xdt="http://www.w3.org/2004/07/xpath-datatypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1441_01.xsd">
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-16T05:02:00</Beginn>
    <Dauer>11</Dauer>
    <Umsatz>11</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-16T06:02:00</Beginn>
    <Dauer>78</Dauer>
    <Umsatz>78</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-16T07:02:00</Beginn>
    <Dauer>17</Dauer>
    <Umsatz>17</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-16T08:02:00</Beginn>
    <Dauer>327</Dauer>
    <Umsatz>327</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-16T09:02:00</Beginn>
    <Dauer>11</Dauer>
    <Umsatz>11</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-16T10:02:00</Beginn>
    <Dauer>123</Dauer>
    <Umsatz>182</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-16T11:02:00</Beginn>
    <Dauer>8</Dauer>
    <Umsatz>12</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-16T12:02:00</Beginn>
    <Dauer>223</Dauer>
    <Umsatz>223</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-17T01:02:00</Beginn>
    <Dauer>2</Dauer>
    <Umsatz>1</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-17T02:02:00</Beginn>
    <Dauer>182</Dauer>
    <Umsatz>266</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-17T03:02:00</Beginn>
    <Dauer>116</Dauer>
    <Umsatz>58</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-17T04:02:00</Beginn>
    <Dauer>173</Dauer>
    <Umsatz>104</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-02-17T06:02:00</Beginn>
    <Dauer>189</Dauer>
    <Umsatz>189</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-05-13T03:05:00</Beginn>
    <Dauer>421</Dauer>
    <Umsatz>366</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-05-13T04:05:00</Beginn>
    <Dauer>444</Dauer>
    <Umsatz>301</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-05-13T05:05:00</Beginn>
    <Dauer>565</Dauer>
    <Umsatz>515</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-05-13T06:05:00</Beginn>
    <Dauer>186</Dauer>
    <Umsatz>186</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Bochum</Stadt>
    <Beginn>2004-05-13T07:05:00</Beginn>
    <Dauer>225</Dauer>
    <Umsatz>225</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-04-28T05:04:00</Beginn>
    <Dauer>342</Dauer>
    <Umsatz>273</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-04-28T06:04:00</Beginn>
    <Dauer>83</Dauer>
    <Umsatz>83</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-04-28T07:04:00</Beginn>
    <Dauer>219</Dauer>
    <Umsatz>219</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-04-28T08:04:00</Beginn>
    <Dauer>245</Dauer>
    <Umsatz>245</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-04-28T09:04:00</Beginn>
    <Dauer>180</Dauer>
    <Umsatz>180</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-04-28T10:04:00</Beginn>
    <Dauer>202</Dauer>
    <Umsatz>242</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-04-28T11:04:00</Beginn>
    <Dauer>198</Dauer>
    <Umsatz>298</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-08T08:06:00</Beginn>
    <Dauer>634</Dauer>
    <Umsatz>634</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-08T09:06:00</Beginn>
    <Dauer>238</Dauer>
    <Umsatz>238</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-08T10:06:00</Beginn>
    <Dauer>931</Dauer>
    <Umsatz>1082</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-08T11:06:00</Beginn>
    <Dauer>225</Dauer>
    <Umsatz>338</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-08T12:06:00</Beginn>
    <Dauer>221</Dauer>
    <Umsatz>161</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-09T01:06:00</Beginn>
    <Dauer>305</Dauer>
    <Umsatz>345</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-09T02:06:00</Beginn>
    <Dauer>180</Dauer>
    <Umsatz>213</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-09T03:06:00</Beginn>
    <Dauer>348</Dauer>
    <Umsatz>289</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-09T04:06:00</Beginn>
    <Dauer>426</Dauer>
    <Umsatz>349</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-09T05:06:00</Beginn>
    <Dauer>646</Dauer>
    <Umsatz>576</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-06-09T06:06:00</Beginn>
    <Dauer>493</Dauer>
    <Umsatz>493</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-08T09:12:00</Beginn>
    <Dauer>424</Dauer>
    <Umsatz>424</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-08T10:12:00</Beginn>
    <Dauer>1399</Dauer>
    <Umsatz>1789</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-08T11:12:00</Beginn>
    <Dauer>526</Dauer>
    <Umsatz>794</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-08T12:12:00</Beginn>
    <Dauer>1415</Dauer>
    <Umsatz>1163</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T01:12:00</Beginn>
    <Dauer>1130</Dauer>
    <Umsatz>1303</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T02:12:00</Beginn>
    <Dauer>1289</Dauer>
    <Umsatz>1553</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T03:12:00</Beginn>
    <Dauer>1253</Dauer>
    <Umsatz>754</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T04:12:00</Beginn>
    <Dauer>1032</Dauer>
    <Umsatz>792</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T05:12:00</Beginn>
    <Dauer>1073</Dauer>
    <Umsatz>730</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T06:12:00</Beginn>
    <Dauer>1224</Dauer>
    <Umsatz>1224</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T07:12:00</Beginn>
    <Dauer>780</Dauer>
    <Umsatz>780</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T08:12:00</Beginn>
    <Dauer>1553</Dauer>
    <Umsatz>1553</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T09:12:00</Beginn>
    <Dauer>1465</Dauer>
    <Umsatz>1465</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T10:12:00</Beginn>
    <Dauer>1346</Dauer>
    <Umsatz>1765</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T11:12:00</Beginn>
    <Dauer>435</Dauer>
    <Umsatz>656</Umsatz>
  </Umsatz>
  <Umsatz>
    <Stadt>Duisburg</Stadt>
    <Beginn>2004-12-09T12:12:00</Beginn>
    <Dauer>1175</Dauer>
    <Umsatz>1161</Umsatz>
  </Umsatz>
</Umsatz-Pro-Stadt>
