=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/04_Kontrollstrukturen/411_01.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by tester (altova) -->
<!--W3C Schema generated by XMLSPY v5 U (http://www.xmlspy.com)-->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Kundenliste">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Kunde" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name">
                <xs:complexType>
                  <xs:choice>
                    <xs:sequence>
                      <xs:element name="Firma" type="xs:string"/>
                      <xs:element name="Branche" type="xs:string"/>
                    </xs:sequence>
                    <xs:sequence>
                      <xs:element name="Nachname" type="xs:string"/>
                      <xs:element name="Vorname" type="xs:string"/>
                    </xs:sequence>
                  </xs:choice>
                </xs:complexType>
              </xs:element>
              <xs:element name="Umsatz" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="Typ" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== firak01/buch_XsltXpathXQuery/XSLTTransformation/file/04_Kontrollstrukturen/411_01.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="422_01.xslt"?>
<Kundenliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="411_01.xsd">
  <Kunde Typ="g">
    <Name>
      <Firma>Gebrüder Mondschein GmbH</Firma>
      <Branche>Seile</Branche>
    </Name>
    <Umsatz>75.95</Umsatz>
  </Kunde>
  <Kunde Typ="p">
    <Name>
      <Nachname>Erdle</Nachname>
      <Vorname>Johann</Vorname>
    </Name>
    <Umsatz>229.45</Umsatz>
  </Kunde>
  <Kunde Typ="p">
    <Name>
      <Nachname>Reifenscheidt</Nachname>
      <Vorname>Vladimir</Vorname>
    </Name>
    <Umsatz>92.91</Umsatz>
  </Kunde>
  <Kunde Typ="g">
    <Name>
      <Firma>Fleckner + Söhne GmbH + Co. KG</Firma>
      <Branche>Fördergurte Gummi Kunststoffe</Branche>
    </Name>
    <Umsatz>703.43</Umsatz>
  </Kunde>
</Kundenliste>
